import streamlit as st

#Streamlit run Introduccion.py

st.set_page_config(page_title = 'PI_2', #Nombre de la pagina, sale arriba cuando se carga streamlit
                   page_icon = 'clipboard:', # https://www.webfx.com/tools/emoji-cheat-sheet/
                   layout="wide")
st.subheader(':ambulance: Reporte PI2 DA - Siniestros Viales') #Titulo del Dash
# st.markdown('***')
st.image("statics//caba.png", use_column_width=True)

st.markdown('###')
st.subheader('Presentacion del Problema:')

st.write("<p>En Buenos Aires, los siniestros viales representan una amenaza significativa para la seguridad pública. Estos accidentes, que involucran vehículos y peatones, resultan en daños materiales y, frecuentemente, en lesiones graves o muertes. En Argentina, con un promedio de 4.000 muertes anuales, los siniestros viales son la principal causa de muertes violentas. Entre 2018 y 2022, se registraron 19.630 fallecimientos, lo que se traduce en 11 víctimas fatales diarias. En 2022, 3.828 personas perdieron la vida en accidentes de tránsito, lo que evidencia la urgencia de abordar esta problemática.</p>", unsafe_allow_html=True)
st.markdown('###')
st.write("<p>La alta tasa de mortalidad por siniestros viales en Argentina, significativamente mayor que otras causas de muertes violentas, subraya la necesidad de intervenciones efectivas. Estas incluyen la educación vial, el cumplimiento de normas de tráfico, la mejora de la infraestructura vial y la promoción de vehículos más seguros. Un análisis detallado y el seguimiento de estadísticas son fundamentales para entender mejor el problema y formular políticas eficaces.</p>", unsafe_allow_html=True)
st.markdown('###')
st.write("<p>El Observatorio de Movilidad y Seguridad Vial (OMSV) de la Secretaría de Transporte de Buenos Aires nos ha encargado un proyecto de análisis de datos para ayudar a reducir las víctimas fatales en siniestros viales. Nos han proporcionado un dataset en formato xlsx con datos sobre homicidios en siniestros viales en Buenos Aires entre 2016 y 2021 y datos sobre lesionados en siniestros viales en Buenos Aires entre 2019 y 2021 (estos incluye Lesionados sea o no con homicidios). Este dataset incluye cuatro hojas principales: hechos y víctimas con homicidios y hechos y victimas de lesionados con o sin homicidios, junto con diccionarios de datos para facilitar la comprensión.</p>", unsafe_allow_html=True)
st.markdown('###')
st.subheader('Hallazgos y Conclusiones:')
st.write("<p>Tipo de Victima: Los accidentes muestran como pareto y con alta frecuencia comparativa donde las victimas son Motorizados o Peatones.</p>", unsafe_allow_html=True)
st.write("<p>Relacion Lesionados - Homicidios: La tendencia de ocurrencia entre Lesionados y Homicidios se mantiene a lo largo del tiempo.</p>", unsafe_allow_html=True)
st.write("<p>Factores de Riesgo: Son factores de influencia La edad y el género de las víctimas, donde la mayoria son Hombres en edades 25 - 40 años.</p>", unsafe_allow_html=True)
st.write("<p>Zonas Críticas: No se Observa una gran influencia de la ubicación geografica, ya que los accidentes ocurren en forma muy distribuida en la ciudad.</p>", unsafe_allow_html=True)
st.write("<p>Tendencia de los Siniestros: Se observa una completa falta de tendencia, no hay una estabilidad ni en alza ni en baja. </p>", unsafe_allow_html=True)
st.markdown('###')
st.write("<p>Educación y Concientización: Campañas dirigidas a grupos de alto riesgo y durante períodos críticos, haciendo un gran enfasis en el correcto uso de cascos y mantener canal de circulacion para motorizados; como en los Peatones solo cruzar por puntos de cruce peatonal, respetar semaforos, no arriesgar al cruzar pensando que no habria problemas.</p>", unsafe_allow_html=True)
st.write("<p>Infraestructura Vial: Mejoras en las zonas con alta incidencia de accidentes, como semáforos adicionales y mejor señalización, considerar la necesidad del peaton de coincidir por canales compartidos con vehiculos, garantizar todos los cruces necesarios.</p>", unsafe_allow_html=True)
st.write("<p>Políticas de Tráfico: Refuerzo del cumplimiento de normas y políticas más estrictas en períodos de alto riesgo, Exigir a Motorizados el correcto uso de indumentaria con proteccion asi como respeto en los canales de circulacion y velocidades limites.</p>", unsafe_allow_html=True)
st.write("<p>Estas recomendaciones proporcionan a las autoridades locales herramientas basadas en datos para tomar decisiones informadas y reducir significativamente las víctimas fatales en siniestros viales, mejorando la seguridad vial en Buenos Aires.</p>", unsafe_allow_html=True)
st.markdown('###')
st.subheader('KPIs:')
st.write("<p>-. Reducir en un 10% la tasa de homicidios en siniestros viales de los últimos seis meses en CABA, en comparación con la tasa de homicidios en siniestros viales del semestre anterior.</p>", unsafe_allow_html=True)
st.write("<p>Los valores Positivos en la columna 'REDUCCION' nos indica una reduccion respecto al semestre anterior, por su lado valores negativos indica un aumento. es conveniente evaluar que se ha hecho y dejado de hacer, ya que no existe ningun tipo de tendencia en la reduccion de Homicidios.</p>", unsafe_allow_html=True)
st.write("<p>Si se ha hecho algun plan de accion este no ha surtido efecto buscado, aunque la falta de tendencia muestra posiblemente que no se ha trabajado ningun plan de accion atacando causas raices.</p>", unsafe_allow_html=True)
st.markdown('###')
st.write("<p>-. Reducir en un 7% la cantidad de accidentes mortales de motociclistas en el último año, en CABA, respecto al año anterior.</p>", unsafe_allow_html=True)
st.write("<p>Valores positivos en la columna 'EVOLUCION_ANUAL' indica reduccion porcentual respecto al año anterior, por su lado valores negativos indica aumento porcentual respecto al año anterior.</p>", unsafe_allow_html=True)
st.write("<p>De manera inmediata podemos repetir parte de las conclusiones en el KPI anterior.</p>", unsafe_allow_html=True)
st.write("<p>Si se ha hecho algun plan de accion este no ha surtido efecto buscado, aunque la falta de tendencia muestra posiblemente que no se ha trabajado ningun plan de accion atacando causas raices.</p>", unsafe_allow_html=True)
st.write("<p>En analisis anteriores vimos que Motos y Peatones eran la mayor proporcion de Victimas Mortales de Accidentes de Transito.</p>", unsafe_allow_html=True)
st.write("<p>Si bien hay años donde la reduccion ha estado muy por encima de las metas propuestas en la medicion del KPI, lo que seria muy positivo, tambien vemos que este reduccion se pierde muy facilmente al llegar otro año..</p>", unsafe_allow_html=True)
st.markdown('###')
st.write("<p>-. Aumentar la proporción de lesionados por cada homicidio en un 10% anual, respecto al año anterior.</p>", unsafe_allow_html=True)
st.write("<p>Este KPI se centra en medir y gestionar la relación entre lesionados y homicidios, buscando que cada año se requiera un 10% más de lesionados para que ocurra un homicidio, en comparación con el año anterior. Aunque el objetivo no es incrementar el número de lesionados, en caso de que los incidentes ocurran, queremos asegurarnos de que la tasa de lesionados por homicidio aumente, reflejando una posible mejora en la capacidad de prevención de homicidios.</p>", unsafe_allow_html=True)
st.write("<p>Nuestra META es la reduccion en un 10% del valor de PROPORCION respecto al AÑO anterior.</p>", unsafe_allow_html=True)
st.write("<p>Podemos intuir lo visto en analisis anteriores de KPIs.</p>", unsafe_allow_html=True)
st.write("<p>Si se ha hecho algun plan de accion este no ha surtido efecto buscado, aunque la falta de tendencia muestra posiblemente que no se ha trabajado ningun plan de accion atacando causas raices.</p>", unsafe_allow_html=True)
st.write("<p>Si bien en ultimo año en estudio (2021) existe una considerable reduccion ha PROPORCION no alcanza a la meta propuestas en la medicion del KPI, lo que seria muy positivo si fuera repetitivo, tambien vemos que este reduccion viene de un aumento mucho mayor en la relacion en par de años anteriores.</p>", unsafe_allow_html=True)
st.markdown('###')
st.markdown('###')